[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 1000
src = 'contracts'
test = 'foundry/test'
out = 'foundry/out'
libs = ['lib', 'node_modules']
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@chainlink/contracts/=node_modules/@chainlink/contracts/',
]
solc_version = '0.8.22'

[profile.pool]
test = 'foundry/test/PoolRegistryFuzz.t.sol'

[profile.lossfuzz]
test = 'foundry/test/LossDistributorFuzz.t.sol'

[profile.committee]
test = 'foundry/test/CommitteeFuzz.t.sol'
[profile.pm]
test = 'foundry/test/PolicyManagerFuzz.t.sol'
[profile.rewardfuzz]
test = 'foundry/test/RewardDistributorFuzz.t.sol'
[profile.staking]
test = 'foundry/staking-tests'
[profile.riskfuzz]
test = 'foundry/test/RiskManagerFuzz.t.sol'



[profile.integration]
test = "foundry/integration"
