[profile.default]
src = "src"
test = 'test'
out = 'out'
libs = ['../lib', '../node_modules']
remappings = ["@openzeppelin/=../node_modules/@openzeppelin/", "@chainlink/contracts/=../node_modules/@chainlink/contracts/"]
solc_version = '0.8.20'
via_ir = true
optimizer = true
optimizer_runs = 1000
fs_permissions = [{ access = "read", path = "../" }, { access = "read", path = "../contracts" }, { access = "read", path = "../node_modules" }]
